Desktop/proyecto/proyecto/Areas/Admin/Controllers/HabilidadesController.cs
using Helper;
using Model;
using proyecto.Areas.Admin.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proyecto.Areas.Admin.Controllers
{
    [Autenticado]
    public class HabilidadesController : Controller
    {
        private Habilidad habilidad = new Habilidad();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Listar(AnexGRID grid)
        {
            return Json(habilidad.Listar(grid, SessionHelper.GetUser()));
        }

        public ActionResult Crud(int id = 0)
        {
            if (id == 0) habilidad.Usuario_id = SessionHelper.GetUser();
            else habilidad = habilidad.Obtener(id);

            return View(habilidad);
        }

        public JsonResult Guardar(Habilidad model)
        {
            var rm = new ResponseModel();

            if (ModelState.IsValid)
            {
                rm = model.Guardar();

                if (rm.response)
                {
                    rm.href = Url.Content("~/admin/habilidades/");
                }
            }

            return Json(rm);
        }

        public JsonResult Eliminar(int id)
        {
            return Json(habilidad.Eliminar(id));
        }
    }
}

Desktop/proyecto/proyecto/Areas/Admin/Views/Habilidades/Crud.cshtml
@model Habilidad
@{
    ViewBag.Title = (Model.id > 0 ? Model.Nombre : "Nuevo registro");
}

<h2 class="page-header">
    @(Model.id > 0 ? Model.Nombre : "Nuevo registro")
</h2>

<ol class="breadcrumb">
    <li><a href="~/admin/habilidades">Habilidades</a></li>
    <li class="active">@(Model.id > 0 ? Model.Nombre : "Nuevo registro")</li>
</ol>

@using (Html.BeginForm("Guardar", "Habilidades", FormMethod.Post))
{
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.Usuario_id)

    <div class="form-group">
        @Html.LabelFor(x => x.Nombre)
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Nombre, null, new { @class = "label label-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Dominio)
        <input type="number" name="Dominio" id="Dominio" class="form-control" placeholder="Ingrese el dominio que tiene sobre esta habilidad" min="1" max="100" value="@Model.Dominio" />
        @Html.ValidationMessageFor(x => x.Dominio, null, new { @class = "label label-danger" })
    </div>

    <div class="text-right">
        <button type="submit" data-ajax="true" class="btn btn-primary">Guardar</button>
    </div>
}

Desktop/proyecto/proyecto/Areas/Admin/Views/Habilidades/Index.cshtml
@{
    ViewBag.Title = "Habilidades";
}

<div id="habilidades" class="page">

    <h1 class="page-header remove-margin">
        <a class="btn btn-primary pull-right" href="~/admin/habilidades/crud">Agregar</a>
        Habilidades
    </h1>

    <div id="list"></div>
</div>

<script>
    $(document).ready(function () {
        var agrid = $("#list").anexGrid({
            columnas: [
                { leyenda: 'Nombre', columna: 'Nombre', ordenable: true },
                { leyenda: 'Dominio', columna: 'Dominio', ordenable: true, style: 'width:500px;' },
                { style: 'width:60px' },
            ],
            modelo: [
                {
                    propiedad: 'Nombre', formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/habilidades/crud/")' + obj.id,
                            contenido: valor
                        });
                    }
                },
                {
                    propiedad: 'Dominio', formato: function (tr, obj, valor) {
                        return '<div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="' + valor + '" aria-valuemin="0" aria-valuemax="100" style="width:' + valor + '%;">' + valor + '%</div></div>';
                    }
                },
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/habilidades/eliminar/")' + obj.id,
                            contenido: '<i class="fa fa-trash"></i>',
                            class: 'btn btn-danger btn-xs btn-block btn-eliminar',
                        });
                    }
                },
            ],
            url: '@Url.Content("~/admin/habilidades/listar")',
            paginable: true,
            limite: [20, 60, 100],
            columna: 'id',
            columna_orden: 'DESC'
        });

        agrid.tabla().on('click', '.btn-eliminar', function () {
            if (!confirm('¿Está seguro de eliminar este registro?'))
            {
                return;
            }

            $.post($(this).attr('href'), function (r) {
                if (r.response) agrid.refrescar();
            }, 'json')

            return false;
        })
    })
</script>