Desktop/proyecto/proyecto/Areas/Admin/Controllers/ExperienciaController.cs
using Helper;
using Model;
using proyecto.Areas.Admin.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proyecto.Areas.Admin.Controllers
{
    [Autenticado]
    public class ExperienciaController : Controller
    {
        private Experiencia experiencia = new Experiencia();

        public ActionResult Index(int tipo = 1)
        {
            ViewBag.tipo = tipo;
            ViewBag.Title = tipo == 1 ? "Trabajos realizados" : "Estudios previos";
            return View();
        }

        public JsonResult Listar(AnexGRID grid, int tipo)
        {
            return Json(experiencia.Listar(grid, tipo, SessionHelper.GetUser()));
        }

        public ActionResult Crud(byte tipo = 0, int id = 0)
        {
            if (id == 0) {
                if (tipo == 0) return Redirect("~/admin/experiencia");

                experiencia.Tipo = tipo;
                experiencia.Usuario_id = SessionHelper.GetUser();
            }
            else experiencia = experiencia.Obtener(id);

            return View(experiencia);
        }

        public JsonResult Guardar(Experiencia model)
        {
            var rm = new ResponseModel();

            if (ModelState.IsValid)
            {
                rm = model.Guardar();

                if (rm.response)
                {
                    rm.href = Url.Content("~/admin/experiencia/?tipo=" + model.Tipo);
                }
            }

            return Json(rm);
        }

        public JsonResult Eliminar(int id)
        {
            return Json(experiencia.Eliminar(id));
        }
    }
}

Desktop/proyecto/proyecto/Areas/Admin/Views/Experiencia/Crud.cshtml
@model Experiencia
@{
    ViewBag.Title = (Model.id > 0 ? Model.Nombre : "Nuevo registro");
}

<h2 class="page-header">
    @(Model.id > 0 ? Model.Nombre : "Nuevo registro")
</h2>

<ol class="breadcrumb">
    <li><a href="~/admin/experiencias?tipo=@Model.Tipo">@(Model.Tipo == 1 ? "Trabajos" : "Estudios previos")</a></li>
    <li class="active">@(Model.id > 0 ? Model.Nombre : "Nuevo registro")</li>
</ol>

@using (Html.BeginForm("Guardar", "Experiencia", FormMethod.Post))
{
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.Tipo)
    @Html.HiddenFor(x => x.Usuario_id)

    <div class="form-group">
        @Html.LabelFor(x => x.Nombre)
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Nombre, null, new { @class = "label label-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Titulo)
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Titulo, null, new { @class = "label label-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Desde)
        <div class="input-group">
            <span class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </span>
            @Html.TextBoxFor(x => x.Desde, new { @class = "form-control datepicker" })
        </div>
        @Html.ValidationMessageFor(x => x.Desde, null, new { @class = "label label-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Hasta)
        <div class="input-group">
            <span class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </span>
            @Html.TextBoxFor(x => x.Hasta, new { @class = "form-control datepicker" })
        </div>
        @Html.ValidationMessageFor(x => x.Hasta, null, new { @class = "label label-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Descripcion)
        @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Descripcion, null, new { @class = "label label-danger" })
    </div>

    <div class="text-right">
        <button type="submit" data-ajax="true" class="btn btn-primary">Guardar</button>
    </div>
}

Desktop/proyecto/proyecto/Areas/Admin/Views/Experiencia/Index.cshtml
@{
    int tipo = ViewBag.tipo;
}

<div id="experiencia" class="page">

    <h1 class="page-header remove-margin">
        <a class="btn btn-primary pull-right" href="~/admin/experiencia/crud?tipo=@tipo">Agregar</a>
        @ViewBag.Title
    </h1>

    <div id="list"></div>
</div>

<script>
    $(document).ready(function () {
        var agrid = $("#list").anexGrid({
            columnas: [
                { leyenda: 'Nombre', columna: 'Nombre', ordenable: true },
                { leyenda: 'Titulo', columna: 'Titulo', ordenable: true },
                { leyenda: 'Desde', columna: 'Desde', ordenable: true },
                { leyenda: 'Hasta', columna: 'Hasta', ordenable: true },
                { style: 'width:60px' },
            ],
            modelo: [
                {
                    propiedad: 'Nombre', formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/experiencia/crud/")' + obj.id,
                            contenido: valor
                        });
                    }
                },
                { propiedad: 'Titulo' },
                { propiedad: 'Desde' },
                { propiedad: 'Hasta' },
                {
                    propiedad: 'Nombre', formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/experiencia/eliminar/")' + obj.id,
                            contenido: '<i class="fa fa-trash"></i>',
                            class: 'btn btn-danger btn-xs btn-block btn-eliminar',
                        });
                    }
                },
            ],
            url: '@Url.Content("~/admin/experiencia/listar?tipo=" + tipo)',
            paginable: true,
            limite: [20, 60, 100],
            columna: 'id',
            columna_orden: 'DESC'
        });

        agrid.tabla().on('click', '.btn-eliminar', function () {
            if (!confirm('¿Está seguro de eliminar este registro?'))
            {
                return;
            }

            $.post($(this).attr('href'), function (r) {
                if (r.response) agrid.refrescar();
            }, 'json')

            return false;
        })
    })
</script>